jobs:
  build:
    name: Build on JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode --no-transfer-progress verify javadoc:jar ${{ matrix.extra-mvn-args
        || '' }}
    strategy:
      matrix:
        include:
        - extra-mvn-args: -Denforcer.fail=false
          java: 21
        java:
        - 11
        - 17
  native-image-test:
    name: GraalVM Native Image test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Set up GraalVM
      uses: graalvm/setup-graalvm@2f25c0caae5b220866f732832d5e3e29ff493338
      with:
        cache: maven
        distribution: graalvm
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: '17'
    - continue-on-error: true
      name: Build and run tests
      run: mvn test --batch-mode --no-transfer-progress --activate-profiles native-image-test
        --projects test-graal-native-image --also-make
  verify-reproducible-build:
    name: Verify reproducible build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Verify no plugin issues
      run: mvn artifact:check-buildplan --batch-mode --no-transfer-progress
    - continue-on-error: true
      name: Verify reproducible build
      run: 'mvn clean install --batch-mode --no-transfer-progress -Dproguard.skip
        -DskipTests

        # Run with `-Dbuildinfo.attach=false`; otherwise `artifact:compare` fails
        because it creates a `.buildinfo` file which

        # erroneously references the existing `.buildinfo` file (respectively because
        it is overwriting it, a file with size 0)

        # See https://issues.apache.org/jira/browse/MARTIFACT-57

        mvn clean verify artifact:compare --batch-mode --no-transfer-progress -Dproguard.skip
        -DskipTests -Dbuildinfo.attach=false

        '
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
permissions:
  contents: read
