jobs:
  check-api-compatibility:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out old version
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      with:
        path: gson-old-japicmp
        ref: ${{ github.event.pull_request.base.sha }}
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build old version
      run: 'cd gson-old-japicmp

        # Set dummy version

        mvn --batch-mode --no-transfer-progress org.codehaus.mojo:versions-maven-plugin:2.16.2:set
        "-DnewVersion=0.0.0-JAPICMP-OLD"

        # Install artifacts with dummy version in local repository; used later by
        Maven plugin for comparison

        mvn --batch-mode --no-transfer-progress install -DskipTests

        '
    - continue-on-error: true
      name: Check out new version
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      id: check-compatibility
      name: Check API compatibility
      run: 'mvn --batch-mode --fail-at-end --no-transfer-progress package japicmp:cmp
        -DskipTests

        '
    - continue-on-error: true
      if: success() || ( failure() && steps.check-compatibility.outcome == 'failure'
        )
      name: Upload API differences artifacts
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
      with:
        if-no-files-found: error
        name: api-differences
        path: '**/japicmp/default-cli.html

          **/japicmp/default-cli.diff

          '
name: Check API compatibility
on:
  repository_dispatch:
    types: trigger-ga___check-api-compatibility.yml
