jobs:
  check-android-compatibility:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Check Android compatibility
      run: '# Run ''test'' phase because plugin normally expects to be executed after
        tests have been compiled

        # Have to skip ''test-jpms'' module because it requires that full Gson JAR
        has been built

        mvn --batch-mode --no-transfer-progress test animal-sniffer:check@check-android-compatibility
        -DskipTests --projects ''!test-jpms''

        '
name: Check Android compatibility
on:
  repository_dispatch:
    types: trigger-ga___check-android-compatibility.yml
permissions:
  contents: read
